### ISSUE TITLE
add built in anti-vpn/proxy detection system

### ISSUE THREAD

**Issue by ProtoGhost** [2lstudios-mc/FlameCord#137]
add a built-in anti-VPN/proxy detection system to block bots and hackers. 
you can able to use  proxychecker.io, iphub.info API for that

**Comment by xIsm4** [comment]
> add a built-in anti-VPN/proxy detection system to block bots and hackers. you can able to use proxychecker.io, iphub.info API for that

I thing that is an ass thing for an open source software, at least if you want an optimal anti-proxy service.
Rate-limit would be so fast, wich means that a simple bot attack would get it.

**Comment by ProtoGhost** [comment]
I'm suggesting anti-vpn for multipurpose to stop vpn user and bot

**Comment by xIsm4** [comment]
> I'm suggesting anti-vpn for multipurpose to stop vpn user and bot

Use external software like Kauri antivpn

**Comment by ProtoGhost** [comment]
No i will not use external

**Comment by ProtoGhost** [comment]
@linsaftw can you do it real quick? waiting from long time please do it

**Comment by ProtoGhost** [comment]
Please add whitelist cmd too, antiVPN on off feature

**Comment by linsaftw** [comment]
What service can we use?

**Comment by xIsm4** [comment]
> What service can we use?

Without paying or hosting one really nothing, and the 2 options in your case are "unfeasible":

Imagine you dare to host one, it's like starting from 0, you will have to go blocking millions of proxies manually and remotely for time, therefore it would be easy to jump and expensive to maintain, the second option is also somewhat expensive, since one sinlge license on proxycheck for example comes out to 20$ for 600k requests per day (Easy overcome in bots attacks to multiple instances) it is simply better to use other software.
