### ISSUE TITLE
Compatibility with a plugin (BungeeTabListPlus)

### ISSUE THREAD

**Issue by Baba1408** [2lstudios-mc/FlameCord#171]
Hello, for some time, I have a problem with a plugin (BungeeTabListPlus) which does not seem compatible with FlameCord, I wanted to know if it would be possible to solve this bug.

Explanatory video (about the tablist) :

> https://youtu.be/4njQE3XZdNo

Hopefully you can solve this bug.
Baba.

**Comment by Baba1408** [comment]
PS: This works perfectly with the original WaterFall, but each player must be under his category (server)

**Comment by xIsm4** [comment]
> PS: This works perfectly with the original WaterFall, but each player must be under his category (server)

FlameCord does not respect the stability of Waterfall itself, delete the "Remove entity metadata" patch and recompile it. This plugin that requires it will work for you.
https://github.com/2lstudios-mc/FlameCord/blob/master/Waterfall-Proxy-Patches/0031-Disable-entity-Metadata-Rewrite.patch

**Comment by linsaftw** [comment]
We are not removing the Entity Metadata Rewrite patch because it makes the server use lot's of CPU.

I recommend not using this plugin either if it requires that feature.

**Comment by Baba1408** [comment]
This is the only problem I have with your Fork, I don't think it will change much since I have a good server, I wanted to know how it is done as compiled without the "Entity Metadata Rewrite"

**Comment by linsaftw** [comment]
> This is the only problem I have with your Fork, I don't think it will change much since I have a good server, I wanted to know how it is done as compiled without the "Entity Metadata Rewrite"

EntityRewrite patch is huge and it's not possible to compile without the patch.

That's the reason i had to close this issue, it's too hard to maintain just for compatibility for one plugin, plus, you really DON'T want to enable Entity Rewrite just because of a tab list... It will make your server vulnerable to many attacks just because of a tab list.

To enable this i have to copy the entire buffer of the packet, which will make many attacks to crash the entire server.

**Comment by andreasdc** [comment]
BTLP works for me and I don't have entity rewriting btw.

**Comment by linsaftw** [comment]
> BTLP works for me and I don't have entity rewriting btw.

So it's working for you on FlameCord ?

**Comment by Baba1408** [comment]
> BTLP works for me and I don't have entity rewriting btw.

I would like to know how you do it if it is possible please? (maybe the configuration file or something else)

**Comment by xIsm4** [comment]
> I would like to know how you do it if it is possible please? (maybe the configuration file or something else)

Read properly please, i said that he could remove it manually and re-build it without the patch. 
And well, as I have already explained several times this patch is not only unstable but also redundant. Since waterfall makes an empty copy when activating its option.
The only thing I would do, would be to prevent packets from being re-compressed as IvanCord fixed in the Janmn14 patch. That does have an effect.

It is also important to differentiate between performance and stability.

**Comment by xIsm4** [comment]
> list.
> 
> To enable this i have to copy the entire buffer of the packet, which will make many attacks to crash the entire server.

And this would not be a problem, if the exceptions thrown by this attack were cached with a trace-less system before they occur, sub-called with QuietException since they are somewhat low on the "error" theme.

**Comment by xIsm4** [comment]
> > BTLP works for me and I don't have entity rewriting btw.
> 
> I would like to know how you do it if it is possible please? (maybe the configuration file or something else)

Just remove the patch for yourself, and re-build the proxy

**Comment by andreasdc** [comment]
> > BTLP works for me and I don't have entity rewriting btw.

Try using IvanCord

**Comment by xIsm4** [comment]
> > > BTLP works for me and I don't have entity rewriting btw.



> > > list.
> > > To enable this i have to copy the entire buffer of the packet, which will make many attacks to crash the entire server.
> > 
> > 
> > And this would not be a problem, if the exceptions thrown by this attack were cached with a trace-less system before they occur, sub-called with QuietException since they are somewhat low on the "error" theme.
> 
> The usage is not during attacks exactly but during high player load.

It may be due to other things, as owners of servers with general traffic (200-400) people have been testing the 2 after the implementation of completely deleting the entity meta data, and the change is barely noticeable.
