### ISSUE TITLE
AntiBot Packets check can not be disabled

### ISSUE THREAD

**Issue by nhanledev** [2lstudios-mc/FlameCord#179]
Hello I am just testing the latest commit and find out that `antibot.packets.enable` can not be set to `false`. It still works if is set to false.

What to expect: it should not cancel packet when disabled.

![image](https://user-images.githubusercontent.com/28459250/210158426-31054e24-a115-4ad0-92b2-93d3d2f043b0.png)

**Comment by xIsm4** [comment]
> Hello I am just testing the latest commit and find out that `antibot.packets.enable` can not be set to `false`. It still works if is set to false.
> 
> What to expect: it should not cancel packet when disabled.
> 
> ![image](https://user-images.githubusercontent.com/28459250/210158426-31054e24-a115-4ad0-92b2-93d3d2f043b0.png)

Try to put a higher number on max bytes, packets etc...

**Comment by linsaftw** [comment]
Lets talk about why do you want to disable it in the first place. I would love to know your thoughts. Do you want a bypass for 127.0.0.1 connections?

**Comment by nhanledev** [comment]
I originally have an issue with this when putting a lot of SafariNet (a kind of item that store mob) items inside a shulker box. I get disconnected everytime I move it with invsee feature. 

Then I try to disable that first. The config is there so I assume that I could set it to false, but it doesn't work so I think it's a bug. 

I ended up increasing the `vls` instead.

**Comment by nhanledev** [comment]
I don't really need a bypass because this is really not necessary when I only need to replicate the dev environment to be the exact same online server to test as much as I can. Because of that, allowing this feature to be disabled is better than whitelisting IPs in my opinion :)

**Comment by linsaftw** [comment]
> I originally have an issue with this when putting a lot of SafariNet (a kind of item that store mob) items inside a shulker box. I get disconnected everytime I move it with invsee feature.
> 
> Then I try to disable that first. The config is there so I assume that I could set it to false, but it doesn't work so I think it's a bug.
> 
> I ended up increasing the `vls` instead.

No no and no. You don't want to DISABLE the entire thing, you want it to adapt to your server needs. For that, you need to decrease the vls added by those shulkers and other kind of stuff you are having problems with.

Try playing with `vls-per-byte`, reducing it until you dont have anymore problems with those items. This way the security will still be present but bypass the items in question.

But I find one thing unviable for your server and its that having items that big and allowing them means players will be able to crash the serrver by using them. FlameCord blocks that amount of data because its harmful, even when used from normal player environments.

But anyways, your option for now is to play with the option I mentioned to allow items that big.
